language: python
python:
    - '2.7'

branches:
  only:
  - master
  - dev

cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio
    - platformio update

script:
    - platformio run

